name: Build and publish docker container

on:
  push:
    tags: ["**"]

jobs:
  check:
    uses: ./.github/workflows/check.yaml
  release:
    runs-on: ubuntu-22.04
    needs: [check]
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/CthulhuDen/dst
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64,linux/arm64
          pull: true
          push: true
