name: Test for docker build

on:
  push:
    branches: ["**"]

jobs:
  check:
    uses: ./.github/workflows/check.yaml
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        uses: docker/build-push-action@v5
        with:
          pull: true
